packages:
  - scripts

allowBuilds:
  esbuild: true

ignoreWorkspaceRootCheck: true

minimumReleaseAgeExclude:
  - prettier@3.8.4

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
  vite-plus: 0.1.24

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
